#!/bin/bash
# Laravel Installer
# Script by Juan
# 
# Illegal selling and redistribution of this script is strictly prohibited
# Please respect author's Property
# Binigay sainyo ng libre, ipamahagi nyo rin ng libre.
#
#

 # Now check if our machine is in root user, if not, this script exits
 # If you're on sudo user, run `sudo su -` first before running this script
if [[ $EUID -ne 0 ]];then
 ScriptMessage
 echo -e "[\e[1;31mError\e[0m] This script must be run as root, exiting..."
 exit 1
fi

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors

Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan


function ip_address(){
  local IP="$( ip addr | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\." | head -n 1 )"
  [ -z "${IP}" ] && IP="$( wget -qO- -t1 -T2 ipv4.icanhazip.com )"
  [ -z "${IP}" ] && IP="$( wget -qO- -t1 -T2 ipinfo.io/ip )"
  [ ! -z "${IP}" ] && echo "${IP}" || echo
} 
IPADDR="$(ip_address)"

function Updating() {
    sudo apt update

}

function InstallApache2() {
    sudo apt install apache2 -y 
    sudo ufw allow "Apache Full"

}

function InstallMySQL() {
    sudo apt install mysql-server -y
    sudo mysql_secure_installation

}

function Installphpmyadmin() {
    sudo apt install phpmyadmin php-mbstring php-zip php-gd php-json php-curl -y
    ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
    sudo phpenmod mbstring
    sudo systemctl restart apache2

}


function InstallComposer() {
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer
}

function Laravel() {
    cd /var/www/html
    echo -e "Hit Enter When Ask to run for root"
    read -p "Enter Folder Name for Laravel:" APP
    composer create-project laravel/laravel ${APP}
    cd /var/www/html/${APP}
    php artisan
    chown -R www-data:www-data /var/www/html/${APP}
    chmod -R 775 /var/www/html/${APP}/storage
    ln -s /usr/share/phpmyadmin /var/www/html/${APP}/public
    apt install npm -y
    npm install 
    npm fund
    echo "<VirtualHost *:80>
            ServerAdmin webmaster@domain.com
            DocumentRoot /var/www/html/${APP}/public
            <Directory /var/www/html/${APP}>
                AllowOverride All
            </Directory>
                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
        </VirtualHost>" > /etc/apache2/sites-available/000-default.conf && service apache2 restart
    sudo apt-get install libssh2-1 php-ssh2 -y
}



function ScriptMessage(){
 echo -e ""
 echo -e " \033[0;36m(｡◕‿◕｡)\033[0m \033[0;31mLaravel Installer \033[0m"
 echo -e " \033[0;31m Script Created:\033[0m \033[0;36mGVPNHUB-Juan\033[0m"
 echo -e ""

}

# Start of Installing Every Function
 
 ScriptMessage
 
 sleep 2

echo -e "\033[0;33m Updatin... \033[0m"
Updating

echo -e "\033[0;33m Installing Apache2...\033[0m"
InstallApache2

echo -e "\033[0;33m Installing MySQL... \033[0m"
InstallMySQL

echo -e "\033[0;33m Installing phpmyadmin... \033[0m"
Installphpmyadmin

echo -e "\033[0;33m Installing Composer... \033[0m"
InstallComposer

echo -e "\033[0;33m Installing Laravel... \033[0m"
Laravel

clear 

# showing Additional Info
ScriptMessage

echo -e ""
echo -e "\033[0;33m Success Installation \033[0m"
echo -e "\033[0;35m phpmyadmin: $IPADDR/phpmyadmin \033[0m"
echo -e "\033[0;36m To Setup phpmyadmin pass run: \033[0m"
echo -e "\033[0;31m 1.) mysql \033[0m"
echo -e "\033[0;31m 2.) ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'set_pass'; \033[0m"
echo -e "\033[0;31m 3.) exit \033[0m"
echo -e ""
echo -e "\033[0;33m Script NOT FOR SALE \033[0m"
echo -e "\033[0;33m REPORT to kakatol@ninjadns.net \033[0m"

 # Clearing all logs from installation
 rm -rf /root/.bash_history && history -c && echo '' > /var/log/syslog

rm -rf /root/installer*

exit 1
